"""add words_total to level_progress

Revision ID: 4a0ae6c0f3bb
Revises: da29c6382689
Create Date: 2025-06-16 18:43:54.900654

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a0ae6c0f3bb"  # pragma: allowlist secret
down_revision: Union[str, None] = "da29c6382689"  # pragma: allowlist secret
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "level_progress", sa.Column("words_total", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("level_progress", "words_total")
    # ### end Alembic commands ###
