"""add level field to words

Revision ID: da29c6382689
Revises: 8df586ccd4c4
Create Date: 2025-06-16 09:59:20.138817

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da29c6382689"
down_revision: Union[str, None] = "8df586ccd4c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "daily_progress", ["id"])
    op.create_unique_constraint(None, "gpt_logs", ["id"])
    op.create_unique_constraint(None, "level_progress", ["id"])
    op.create_unique_constraint(None, "test_sessions", ["id"])
    op.create_unique_constraint(None, "token_blacklist", ["id"])
    op.create_unique_constraint(None, "user_settings", ["id"])
    op.create_unique_constraint(None, "user_stats", ["id"])
    op.create_unique_constraint(None, "user_words", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    op.add_column(
        "words",
        sa.Column(
            "level", sa.String(length=8), nullable=True, comment="CEFR рівень слова: A1, A2, B1..."
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("words", "level")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "user_words", type_="unique")
    op.drop_constraint(None, "user_stats", type_="unique")
    op.drop_constraint(None, "user_settings", type_="unique")
    op.drop_constraint(None, "token_blacklist", type_="unique")
    op.drop_constraint(None, "test_sessions", type_="unique")
    op.drop_constraint(None, "level_progress", type_="unique")
    op.drop_constraint(None, "gpt_logs", type_="unique")
    op.drop_constraint(None, "daily_progress", type_="unique")
    # ### end Alembic commands ###
